#!/bin/bash

# SPDX-FileCopyrightText: © 2026 Jeffrey C. Ollie
# SPDX-License-Identifier: MIT

counter=0
while (($(nix run nixpkgs#sqlite -- "$NIKS3_TMP_DIR/upload-queue.db" 'SELECT COUNT(*) from upload_queue;') > 0)) && ((counter < 60))
do
  echo "waiting for server to finish..."
  ((counter++))
  sleep 1
done

# try and kill the "serve" background command
pid=$(cat "$NIKS3_TMP_DIR/serve.pid")
if [[ -n "$pid" ]]; then
  kill "$pid"
fi

echo "--- :notebook: 'niks3 serve' log"
if [[ -f "$NIKS3_TMP_DIR/serve.log" ]]; then
  cat "$NIKS3_TMP_DIR/serve.log"
fi
