#!/bin/bash

# SPDX-FileCopyrightText: © 2026 Jeffrey C. Ollie
# SPDX-License-Identifier: MIT

niks3_url=https://github.com/Mic92/niks3.git

cache_url="$BUILDKITE_PLUGIN_NIKS3_CACHE_CACHE_URL"
if [[ "$cache_url" == "" ]]; then
  echo "Missing cache url configuration."
  exit 1
fi

public_key="$BUILDKITE_PLUGIN_NIKS3_CACHE_PUBLIC_KEY"
if [[ "$public_key" == "" ]]; then
  echo "Missing public key configuration."
  exit 1
fi

server_url="$BUILDKITE_PLUGIN_NIKS3_CACHE_SERVER_URL"
if [[ "$server_url" == "" ]]; then
  echo "Missing server url configuration."
  exit 1
fi

token="$NIKS3_AUTH_TOKEN"
if [[ "$token" == "" ]]; then
  echo "Missing token configuration."
  exit 1
fi

NIKS3_TMP_DIR=$(mktemp -d)
export NIKS3_TMP_DIR

echo "+++ Setting up the Nix post build hook"
nix=$(which nix)

echo "#/bin/sh" > "$NIKS3_TMP_DIR/post-build-hook"
echo "exec \"$nix\" run \"git+${niks3_url}#niks3-hook\" -- send --socket \"$NIKS3_TMP_DIR/upload-to-cache.sock\"" >> "$NIKS3_TMP_DIR/post-build-hook"
chmod a+x "$NIKS3_TMP_DIR/post-build-hook"

echo "+++ Adding the cache to the Nix configuration"
echo "extra-substituters = $cache_url" >> /etc/nix/nix.custom.conf
echo "extra-trusted-public-keys = $public_key" >> /etc/nix/nix.custom.conf

echo "+++ Starting the upload server"

echo "$token" > "$NIKS3_TMP_DIR/auth-token"

nohup "$nix" run "git+${niks3_url}#niks3-hook" -- serve \
  --server-url "$server_url" \
  --auth-token-path "$NIKS3_TMP_DIR/auth-token" \
  --socket "$NIKS3_TMP_DIR/upload-to-cache.sock" \
  --db-path "$NIKS3_TMP_DIR/upload-queue.db" \
  --idle-exit-timeout 0 \
  --batch-size 5 \
  > "$NIKS3_TMP_DIR/serve.log" 2>&1 &
echo "$!" > "$NIKS3_TMP_DIR/serve.pid"

echo "+++ Installing the Nix post build hook"
echo "post-build-hook = $NIKS3_TMP_DIR/post-build-hook" >> /etc/nix/nix.custom.conf
